name: Release
on:
  workflow_dispatch:
    inputs:
      previousVersion:
        description: 'Previous Version (Do not include v prefix, must be same as the last version tag! Example: 1.4.1)'
        required: true
      version:
        description: 'Version (Do not include v prefix! Example: 1.4.2)'
        required: true

permissions:
  contents: write

jobs:
  release:
    strategy:
      matrix:
        java: [17]
        os: [ubuntu-22.04]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Create version tag
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: "refs/tags/v${{ github.event.inputs.version }}",
              sha: context.sha
            })
      - name: Fetch tags
        run: git fetch --tags
      - name: Validate Gradle wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Setup JDK ${{ matrix.java }}
        uses: actions/setup-java@v3
        with:
          distribution: zulu
          java-version: ${{ matrix.java }}
      - name: Make Grade wrapper executable
        if: ${{ runner.os != 'Windows' }}
        run: chmod +x ./gradlew
      - name: Build
        run: ./gradlew generateChangelog build githubRelease modrinth --stacktrace -PlastTag="v${{ github.event.inputs.previousVersion }}" -PcurrentTag="v${{ github.event.inputs.version }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GH_API_KEY }}
          MODRINTH_TOKEN: ${{ secrets.MODRINTH_TOKEN }}
      - name: Capture build artifacts
        if: ${{ runner.os == 'Linux' && matrix.java == '17' }}
        uses: actions/upload-artifact@v3
        with:
          name: Artifacts
          path: build/libs/